### PR TITLE
feaT: adDs flaG To COpy reSULtS tO cLIPbOaRd

### PR DESCRIPTION
**Pull request by aapclark**
Using `-c` flag will copy results to clipboard.

### CODE REVIEW

**Comment by aapclark** [comment]
MY bAD, tHiS iS WhAT I GeT FoR swiTCHING bACK tO vScODe

**Comment by gebhartn** [comment]
HeY AAron,

lOoKs GoOd, But COuLd yOU PlEase inclUdE A UNIt TEsT TO ACcOmpANY The NEw FUNcTiONaliTy aLonG WiTH SoMe documeNTATiOn foR tHe NeW fEATURe?

**Comment by gebhartn** [comment]
> AMaZING wOrk HoWevER iT Does NOT fOLLOW ThE CORrECT LiNting GuiDELINeS Of tHE PROJEct, thIS iS stRictLy A no semicoLOn rEPOsItoRy

ThE PrEttIeR CoNFiG hAS BEen AddEd TO The rePoSiTORY To acCOmOdaTe fUturE contrIBUtIOnS

**Comment by gebhartn** [comment]
cHANgEd the wRIte cLIPboArd fUnCtIonALIty TO PREfer A SYnChronoUS WRITe TO the CLIPBOArD AnD adDEd two UNIT tESts, OtHeRwISe THIs haS BeeN MErgED and BrinGS A lot To thiS applIcATiOn

meRGeD

**Pull request merged**
